### ISSUE TITLE
Failed to find module: "utf8"

### ISSUE THREAD

**Issue by KeyvanMM** [mathiasbynens/utf8.js#32]
Hi
I've added the plugin using:
npm install utf8

and then added this to one page:
var utf8 = require('utf8');

but on navigating to that page i got this error:
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: Failed to find module: "utf8", relative to: app/tns_modules/

I had no problem with other plugins, maybe I forget some thing?

**Comment by pineapplethief** [comment]
Having this too, using webpack and es6 `import utf8 from 'utf8'` syntax. module is present in package.json as far as I can see

**Comment by pineapplethief** [comment]
Oops, it's working now, must have been some webpack or yarn glitch

**Comment by mathiasbynens** [comment]
https://github.com/facebook/react-native/pull/17146
