### ISSUE TITLE
Doesn't encode English

### ISSUE THREAD

**Issue by AbdelrahmanHafez** [mathiasbynens/utf8.js#33]
Using the library on https://mothereff.in/utf-8
When I type in `Hello World!`, I receive the utf-8 representation of it, as `\x48\x65\x6C\x6C\x6F\x20\x57\x6F\x72\x6C\x64\x21`

However, when I use it locally on node, running
```
let value = utf8.encode('Hello World!');
console.log(value); // Hello World!
```
Am I doing something wrong?

**Comment by mathiasbynens** [comment]
Well, those two strings are the same!

```js
'\x48\x65\x6C\x6C\x6F\x20\x57\x6F\x72\x6C\x64\x21' === 'Hello World!';
// → true
```

To get the same output as in the online tool, wrap the result of `utf8.encode` in [jsesc](https://mths.be/jsesc).
