### ISSUE TITLE
Incorrect encoding/decoding

### ISSUE THREAD

**Issue by nuclearace** [mathiasbynens/utf8.js#8]
Maybe I'm crazy but when doing

```JavaScript
 console.log(new Buffer(utf8.encode("π"), 'utf8'))
```
`> <Buffer c3 8f c2 80>`

When I believe the correct encoding should be

`<Buffer cf 80>`

As Swift shows ![](https://i.imgur.com/qkQ3mSK.png)

**Comment by nuclearace** [comment]
Found because my socket.io-client-swift's unicode messages are exploding inside of https://github.com/Automattic/engine.io-parser/blob/master/lib/index.js#L157

For example this string is what's being passed into `decode` ![](http://i.imgur.com/Vk5FW95.png)

**Comment by nuclearace** [comment]
Looking more closely, I believe this might be a problem with engine.io-parser

**Comment by mathiasbynens** [comment]
```
>  console.log(jsesc(utf8.encode('π'), 'utf8'))
\xCF\x80
```

https://mothereff.in/utf-8#%CF%80

I don’t see a problem here.

Please post a link to the engine.io-parser issue once you’ve filed it.

**Comment by nuclearace** [comment]
https://github.com/Automattic/engine.io/issues/315
